"""
Version information for the UoM Deep Learning Workshop utilities package.
Auto-generated by GitHub Actions CI/CD pipeline.
"""

# Version information
__version__ = "1.1.0"
__commit__ = "2afba28"
__version_full__ = "1.1.0+2afba28"
